/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2019-08-12 09:03:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mobile;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<!-- 페이지 크기 제어 사파리용 -->\r\n");
      out.write("<meta name=\"viewport\" content=\"user-scable= no, width=device-width\" />\r\n");
      out.write("<!-- Safari UI(URL Bar, Button Bar) 없애기 및 변경하기 -->\r\n");
      out.write("<meta name=”apple-mobile-web-app-capable” content=”yes” />\r\n");
      out.write("<meta name=”apple-mobile-web-app-status-bar-style” content=”black” />\r\n");
      out.write("\r\n");
      out.write("<!-- 서버에 캐시를 저장하지 않고 정보필요할때마다 서버에 접속 정보를 가져온다 -->\r\n");
      out.write("<meta http-equiv=\"Cache-Control\" content=\"no-cache\" />\r\n");
      out.write("<meta http-equiv=\"Expires\" content=\"0\" /><!-- 캐시만료일 지정 -->\r\n");
      out.write("<meta http-equiv=\"Pragma\" content=\"no-cache\" />\r\n");
      out.write("\r\n");
      out.write("<!-- jsp인클루드로 박는 값들에 부트스트랩 적용 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- include libraries(jQuery, bootstrap) -->\r\n");
      out.write("<!-- 부트스트랩 제대로 돌아가려면 이거 필요 min 말고-->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- include summernote css/js -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t//좌우 회전, 화면 크기 변경 대응\r\n");
      out.write("\tvar orientationEvent;\r\n");
      out.write("\tvar uAgent = navigator.userAgent.toLowerCase();\r\n");
      out.write("\tvar mobilePhones = 'android';\r\n");
      out.write("\tif (uAgent.indexOf(mobilePhones) != -1) {\r\n");
      out.write("\t\torientationEvent = \"resize\"; //안드로이드는 resize로 들어옴\r\n");
      out.write("\t} else\r\n");
      out.write("\t\torientationEvent = \"orientationchange\"; //아이폰은 이렇게 들어옴\r\n");
      out.write("\t\t//이벤트(화면돌리는거) 실행되면\r\n");
      out.write("\twindow.addEventListener(orientationEvent, function() {\r\n");
      out.write("\t\t//\talert(\"회전했어요\");\r\n");
      out.write("\t\tlocation.href('#');//재부팅해서 다시 넓이같으거 계산해서 출력\r\n");
      out.write("\t}, false); //false=버블단계 window에 이벤트는 캡쳐단계와 버블단계 둘중 하나에 걸림 교안 3-2강내용\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t//스크린 나오는 함수\r\n");
      out.write("\tvar prevScreen = 0;\r\n");
      out.write("\tvar sv_prevScreen = 0;\r\n");
      out.write("\tfunction prevShow() {\r\n");
      out.write("\t\tScreenShow(prevScreen);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tvar muCnt = 5;//서브메뉴\r\n");
      out.write("\tvar scCnt = 14;//화면\r\n");
      out.write("\r\n");
      out.write("\tfunction fncShow(pos) {\r\n");
      out.write("\r\n");
      out.write("\t\tvar i = 0;\r\n");
      out.write("\r\n");
      out.write("\t\t//모든 일반 화면 막는다.\r\n");
      out.write("\t\tfor (i = 0; i < scCnt; i++) {\r\n");
      out.write("\t\t\tvar obj = document.getElementById(\"s\" + i);\r\n");
      out.write("\t\t\tobj.style.display = 'none';\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t//메뉴선택에 따라 중간메뉴 div는 보여주고, 누른 버튼의 배경을 바꿔준다\r\n");
      out.write("\t\tfor (i = 0; i < muCnt; i++) {\r\n");
      out.write("\t\t\tvar obj = document.getElementById(\"menu\" + i);\r\n");
      out.write("\t\t\tvar obj2 = document.getElementById(\"m\" + i);\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (i == pos) {\r\n");
      out.write("\t\t\t\tobj.style.display = '';\r\n");
      out.write("\t\t\t\tobj2.style.background = \"#ff0000\";\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tobj.style.display = 'none';\r\n");
      out.write("\t\t\t\tobj2.style.background = \"#FFFF00\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//총 화면은 14개이고 화면이 선택된 번호에 따라 화면을 보여주는 함수\r\n");
      out.write("\tvar scCnt = 14;\r\n");
      out.write("\tvar ScrObj;\r\n");
      out.write("\tvar timer1;\r\n");
      out.write("\r\n");
      out.write("\tfunction ScrAnimation() {\r\n");
      out.write("\t\tvar offset = -50;\r\n");
      out.write("\t\tif (parseInt(ScrObj.style.left) > 10) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tScrObj.style.left = parseInt(ScrObj.style.left) + offset + \"px\";\r\n");
      out.write("\t\t\ttimer1 = setTimeout(\"ScrAnimation()\", 1);\r\n");
      out.write("\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tScrObj.style.left = 5;\r\n");
      out.write("\t\t\tclearTimeout(timer1);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t//화면이 선택된 번호에 따라 화면을 보여주는 함수\r\n");
      out.write("\tfunction ScreenShow(pos) {\r\n");
      out.write("\r\n");
      out.write("\t\tvar i = 0;\r\n");
      out.write("\t\t//모든 메뉴페이지는 막는다\r\n");
      out.write("\t\tfor (i = 0; i < muCnt; i++) {\r\n");
      out.write("\t\t\tvar obj = document.getElementById(\"menu\" + i);\r\n");
      out.write("\t\t\tobj.style.display = 'none';\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t//선택된 하면 번호의 화면만 보여준다.\r\n");
      out.write("\t\tfor (i = 0; i < scCnt; i++) {\r\n");
      out.write("\t\t\tvar obj = document.getElementById(\"s\" + i);\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (i == pos) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tprevScreen = sv_prevScreen;\r\n");
      out.write("\t\t\t\tsv_prevScreen = i;\r\n");
      out.write("\t\t\t\tobj.style.display = '';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tobj.style.position = \"relative\";\r\n");
      out.write("\t\t\t\tobj.style.top = 35;\r\n");
      out.write("\t\t\t\tobj.style.left = screen.width;\r\n");
      out.write("\t\t\t\tobj.style.height = screen.height - 120;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tScrObj = obj;\r\n");
      out.write("\t\t\t\tScrAnimation();\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tobj.style.display = 'none';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("li {\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tmargin: 2;\r\n");
      out.write("\tpadding: 10;\r\n");
      out.write("\theight: 20;\r\n");
      out.write("\tbackground-color: #aaaa00;\r\n");
      out.write("\tborder: 2px solid red;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul {\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tmargin: 2;\r\n");
      out.write("\tpadding: 10;\r\n");
      out.write("\theight: 20;\r\n");
      out.write("\tbackground-color: #bbaabb;\r\n");
      out.write("\tborder: 2px solid red;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 기본 웹페이지를 상단 중단 하단으로 나누고 상하단을 고정 중단은 오버플로우로 스크롤 가능하게한다 */\r\n");
      out.write("#container {\r\n");
      out.write("\theight: 100vh;\r\n");
      out.write("\tdisplay: flex; /* 디스플레이를 플렉스로 준다 */\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#head {\r\n");
      out.write("\theight: 7vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#contents {\r\n");
      out.write("\theight: 81vh;\r\n");
      out.write("\toverflow: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#foot {\r\n");
      out.write("\theight: 11vh;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>m.Resort</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload='ScreenShow(0);'>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<div id=\"container\"\r\n");
      out.write("\t\t\tstyle=\"width: device-width; height: device-height;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 헤더  고정된다 -->\r\n");
      out.write("\t\t\t<div id=\"head\">\r\n");
      out.write("\t\t\t\t<div id=\"header1\"\r\n");
      out.write("\t\t\t\t\tstyle=\"background-color: #00FFFF; height: 35px; width: 15%; float: left;\"\r\n");
      out.write("\t\t\t\t\tonclick=\"prevShow();\">\r\n");
      out.write("\t\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/back_btn.png\" width=\"40px\" height=\"32px\">\r\n");
      out.write("\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"header2\"\r\n");
      out.write("\t\t\t\t\tstyle=\"background-color: #00FFFF; height: 35px; width: 70%; float: left;\">\r\n");
      out.write("\t\t\t\t\t<center style=\"margin: 10px\">\r\n");
      out.write("\t\t\t\t\t\t<B>폴리 리조트</B>\r\n");
      out.write("\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"header3\"\r\n");
      out.write("\t\t\t\t\tstyle=\"background-color: #00FFFF; height: 35px; width: 15%; float: left;\"\r\n");
      out.write("\t\t\t\t\tonclick=\"ScreenShow(0);\">\r\n");
      out.write("\t\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/home_btn.png\" width=\"30px\" height=\"32px\">\r\n");
      out.write("\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 메뉴화면 기본적으로 display가 none인 상태-->\r\n");
      out.write("\t\t\t<div id=\"menu0\"\r\n");
      out.write("\t\t\t\tstyle=\"background-color: #EEEEEE; display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t리조트 소개\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(0);'>폴리리조트</li>\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(1);'>vip룸</li>\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(2);'>일반룸</li>\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(3);'>합리룸</li> <br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"menu1\"\r\n");
      out.write("\t\t\t\tstyle=\"background-color: #EEEEEE; display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t찾아오기\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(4);'>찾아오는길</li>\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(5);'>대중교통이용</li>\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(6);'>자가용이용</li> <br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"menu2\"\r\n");
      out.write("\t\t\t\tstyle=\"background-color: #EEEEEE; display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t주변명소\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(7);'>높아산</li>\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(8);'>시원해수용작</li>\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(9);'>따근온천</li> <br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"menu3\"\r\n");
      out.write("\t\t\t\tstyle=\"background-color: #EEEEEE; display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t예약하기\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(10);'>예약상황</li>\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(11);'>예약하기</li> <br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"menu4\"\r\n");
      out.write("\t\t\t\tstyle=\"background-color: #EEEEEE; display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t리조트소식\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(12);'>공지사항</li>\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(13);'>이용후기</li> <br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 화면 부 메뉴클릭시 뜬다 -->\r\n");
      out.write("\t\t\t<div id=\"contents\">\r\n");
      out.write("\t\t\t\t<div id=\"s0\" style=\"display: none; width: device-width;overflow: overlay;\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- 정적 페이지는 jsp인클루드로 불러옴 부트스트랩으로 이미 반응형 크기이다. -->\r\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../main.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"s1\" style=\"display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../VipRoom.html", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"s2\" style=\"display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../normalRoom.html", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"s3\" style=\"display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../ReasonableRoom.html", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"s4\" style=\"display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "mDirection.html", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"s5\" style=\"display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "mPublicTransit.html", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"s6\" style=\"display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<h1>현재 주차장 바닥 공사로 가급적 대중교통을 이용해 주시기 바랍니다</h1>\r\n");
      out.write("\t\t\t\t\t<br> <br>\r\n");
      out.write("\t\t\t\t\t<h2>죄송합니다. 빠른 시일내로 정상화 하겠습니다.</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"s7\" style=\"display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../Sight1.html", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"s8\" style=\"display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../Sight2.html", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"s9\" style=\"display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../Sight3.html", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"s10\" style=\"display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t\t<!-- \t\t\t\t\t<iframe src=\"mReserve.jsp\" frameborder=\"0\" border=\"0\" -->\r\n");
      out.write("\t\t\t\t\t<!-- \t\t\t\t\t\tbordercolor=\"white\" width=\"320px\" height=\"420px\" margin-width=\"0\" -->\r\n");
      out.write("\t\t\t\t\t<!-- \t\t\t\t\t\tmargin-height=\"0\" scroling=\"yes\">예약상황</iframe> -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- 예약 공지 이용후기는 iframe을 활용하여 한다. -->\r\n");
      out.write("\t\t\t\t\t<iframe src=\"mReserve.jsp\" frameborder=\"0\" border=\"0\"\r\n");
      out.write("\t\t\t\t\t\tbordercolor=\"white\" margin-width=\"0\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: -webkit-fill-available; height: -webkit-fill-available;\"\r\n");
      out.write("\t\t\t\t\t\tmargin-height=\"0\" scroling=\"yes\">예약상황</iframe>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"s11\" style=\"display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t\t<iframe src=\"mReserve.jsp?contentPage=Reserve/Reserve_direct_insert.jsp\" frameborder=\"0\" border=\"0\" bordercolor=\"white\"\r\n");
      out.write("\t\t\t\t\t\tmargin-width=\"0\" margin-height=\"0\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: -webkit-fill-available; height: -webkit-fill-available;\"\r\n");
      out.write("\t\t\t\t\t\tscroling=\"yes\">예약하기</iframe>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"s12\" style=\"display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t\t<iframe src=\"mNotification.jsp\" frameborder=\"0\" border=\"0\" bordercolor=\"white\"\r\n");
      out.write("\t\t\t\t\t\tmargin-width=\"0\" margin-height=\"0\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: -webkit-fill-available; height: -webkit-fill-available;\"\r\n");
      out.write("\t\t\t\t\t\tscroling=\"yes\">공지사항</iframe>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"s13\" style=\"display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t\t<iframe src=\"mComment.jsp\" frameborder=\"0\" border=\"0\" bordercolor=\"white\"\r\n");
      out.write("\t\t\t\t\t\tmargin-width=\"0\" margin-height=\"0\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: -webkit-fill-available; height: -webkit-fill-available;\"\r\n");
      out.write("\t\t\t\t\t\tscroling=\"yes\">이용후기</iframe>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- footer 하단의 메뉴 고정 클릭시마다 fncshow함수가 실행된다.-->\r\n");
      out.write("\t\t\t<!-- 포지션을 absolute로 주었기 때문에 하단에 고정되고 left를 %주어 넓이는 반응형으로 함 -->\r\n");
      out.write("\t\t\t<div id=\"foot\">\r\n");
      out.write("\t\t\t\t<div id=\"m0\" onclick='fncShow(0);'\r\n");
      out.write("\t\t\t\t\tstyle=\"position: absolute; bottom: 3px; position: absolute; left: 1%; background-color: #FF0000; height: 60px; width: 18%; float: left;\">\r\n");
      out.write("\t\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/m1_btn.png\" width=\"40px\" height=\"40px\"><br>\r\n");
      out.write("\t\t\t\t\t\t<font size=1.5>리조트소개</font>\r\n");
      out.write("\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"m1\" onclick='fncShow(1);'\r\n");
      out.write("\t\t\t\t\tstyle=\"position: absolute; bottom: 3px; position: absolute; left: 21%; background-color: #FF0000; height: 60px; width: 18%; float: left;\">\r\n");
      out.write("\t\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/m2_btn.png\" width=\"40px\" height=\"40px\"><br>\r\n");
      out.write("\t\t\t\t\t\t<font size=1.5>찾아오기</font>\r\n");
      out.write("\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"m2\" onclick='fncShow(2);'\r\n");
      out.write("\t\t\t\t\tstyle=\"position: absolute; bottom: 3px; position: absolute; left: 41%; background-color: #FF0000; height: 60px; width: 18%; float: left;\">\r\n");
      out.write("\t\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/m3_btn.png\" width=\"40px\" height=\"40px\"><br>\r\n");
      out.write("\t\t\t\t\t\t<font size=1.5>주변명소</font>\r\n");
      out.write("\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"m3\" onclick='fncShow(3);'\r\n");
      out.write("\t\t\t\t\tstyle=\"position: absolute; bottom: 3px; position: absolute; left: 61%; background-color: #FF0000; height: 60px; width: 18%; float: left;\">\r\n");
      out.write("\t\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/m4_btn.png\" width=\"40px\" height=\"40px\"><br>\r\n");
      out.write("\t\t\t\t\t\t<font size=1.5>예약하기</font>\r\n");
      out.write("\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"m4\" onclick='fncShow(4);'\r\n");
      out.write("\t\t\t\t\tstyle=\"position: absolute; bottom: 3px; position: absolute; left: 81%; background-color: #FF0000; height: 60px; width: 18%; float: left;\">\r\n");
      out.write("\t\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/m5_btn.png\" width=\"40px\" height=\"40px\"><br>\r\n");
      out.write("\t\t\t\t\t\t<font size=1.5>리조트소식</font>\r\n");
      out.write("\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</center>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- jsp인클루드로 박는 값들에 부트스트랩 적용 -->\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
